dist: xenial

language: python

compiler: g++

env:
  global:
    - TRAVIS_CI=true
    - PYTHONPATH=$(pwd)
    - COVERAGE_PROCESS_START="$(pwd)/tox.ini"

cache:
  directories:
    - $HOME/.cache/pip

jobs:
  include:
    - stage: "Tests"
      name: "Lint"
      python: 3.6
      script:
        - pipenv lock --dev --requirements > dev-reqs.txt
        - pip install -r dev-reqs.txt
        - make lint

    - name: "pipenv check"
      python: 3.6
      script:
        - pipenv check || (sleep 60; pipenv check) || (sleep 60; pipenv check)

    - name: "Unit Tests (3.6)"
      python: 3.6
      before_script:
        - ulimit -c unlimited -S       # enable core dumps
      install:
        - pip install pipenv codecov
      script:
        - pipenv lock --requirements > reqs.txt
        - pip install -r reqs.txt
        - sudo apt-get install -y gdb  # install gdb
        - make testcert.cert
        - coverage erase
        - pytest
        - ls -la
        - coverage combine
      after_success:
        - codecov
      after_failure:
        - PYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)")
        - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
        - if [[ -f "$COREFILE" ]]; then
              gdb -c "$COREFILE" $PYTHON_EXECUTABLE -ex "thread apply all bt" -ex "set pagination 0" -batch;
          fi

    - name: "Unit Tests (3.7.4)"
      python: 3.7.4
      before_script:
        - ulimit -c unlimited -S       # enable core dumps
      install:
        - pip install pipenv codecov
      script:
        - pipenv lock --requirements > reqs.txt
        - pip install -r reqs.txt
        - sudo apt-get install -y gdb  # install gdb
        - make testcert.cert
        - coverage erase
        - pytest
        - ls -la
        - coverage combine
      after_success:
        - codecov
      after_failure:
        - PYTHON_EXECUTABLE=$(python3 -c "import sys; print(sys.executable)")
        - COREFILE=$(find . -maxdepth 1 -name "core*" | head -n 1) # find core file
        - if [[ -f "$COREFILE" ]]; then
              gdb -c "$COREFILE" $PYTHON_EXECUTABLE -ex "thread apply all bt" -ex "set pagination 0" -batch;
          fi

    - name: "Unit Tests (3.7.4) (osx)"
      os: osx
      osx_image: xcode11    # Python 3.7.4 running on macOS 10.14.4
      language: shell       # 'language: python' is an error on Travis CI macOS
      script:
        - python3 --version
        - pip3 install -U pip
        - pip3 install -U pytest
        - pip3 install -U -e .
        - pytest
